model_params:
  name: 'BetaVAE'
  in_channels: 3
  latent_dim: 128
  image_size: 64
  beta: 15

exp_params:
  dataset: celeba
  data_path: "../shared/Data/"
  image_size: 128
  batch_size: 144 # Better to have a square number
  sample_batch_size: 36
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "BetaVAE"
  manual_seed: 1265
