model_params:
  name: 'DCGAN'
  in_channels: 3
  latent_dim: 100
  image_size: 64
  batch_size: 128
  feature_maps: 64

exp_params:
  dataset: celeba
  data_path: "/data/kaggle/shared/Data/celeba"
  image_size: 64
  batch_size: 128 # Better to have a square number
  sample_batch_size: 36
  LR: 0.0002
  weight_decay: 0.0
  scheduler_gamma: 0.95
  beta1: 0.5
  work_num: 4

trainer_params:
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "DCGAN"
  manual_seed: 1265
