model_params:
  name: 'SOFT_INTRO_VAE'
  in_channels: 3
  num_embeddings: 512
  image_size: 64
  latent_dim: 256
  batch_size: 64
  beta_kl: 1
  beta_rec: 0.5
  beta_neg: 256
  gamma_r: 0.00000001


exp_params:
  data_set: "beauty"
  resolution: 64
  batch_size: 64 # Better to have a square number
  sample_batch_size: 36
  LR: 0.0002
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 1
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: "SOFT_INTRO_VAE"
  manual_seed: 1265