model_params:
  name: 'StyleGAN2_ADA'
  code_dim: 512


exp_params:
  alpha: 1
  mixing: False
  loss: 'r1'
  code_dim: 512
  data_set: "beauty"
  resolution: 64
  batch_size: 8 # Better to have a square number
  sample_batch_size: 36
  LR: 0.002


trainer_params:
  gpus: 1
  max_epochs: 500

logging_params:
  save_dir: "logs/"
  name: "StyleGAN2_ADA"
  manual_seed: 1265
